version: 2.1
orbs:
  node: circleci/node@4.7.0
  cypress: cypress-io/cypress@1
workflows:
  tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 'lts'
                - '12.22'
              run-command:
                - 'test:unit'
          pkg-manager: yarn
      - cypress/run:
          executor: cypress/base-14
          record: false
      - cypress/run:
          executor: cypress/base-12
          record: false
